[package]
name = "Land"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "Land"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "Land"
path = "Source/Fn/Binary/Land.rs"

[lib]
name = "Library"
path = "Source/Library.rs"

[dependencies]
clap = { version = "4.4.18", features = ["cargo"] }
proc_use = "0.2.1"
rayon = "1.8.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
